### ISSUE TITLE
409 error with Dropbox

### ISSUE THREAD

**Issue by ZeroEkkusu** [fyears/remotely-save#10]
Hi, fyears,

I’m using the plugin for the first time.

There’s a 409 error whenever I try syncing with Dropbox. Only an empty folder with my vault’s name is created inside the `Apps/remotely-save` directory.

I tried setting up everything over again but got the same error.

**Comment by fyears** [comment]
> an empty folder with my vault’s name is created

that folder is created as expected, but the files not being able to sync is not expected.

Could you please create another testing vault and create some random (meaningless, but not empty) notes, and try the plugin again?

And, do you use encryption password or not?

**Comment by ZeroEkkusu** [comment]
Sorry for not providing more information the first time.

I've figured out what's going on, though.

After digging into my files, I found some with long names. I do use encryption password, so, the problem was the same as #5, but with a different error.

**Comment by fyears** [comment]
OK, the latest version uses base64url which is shorter than the previous base32 encoding. But unfortunately the encrypted result is always longer than the unencrypted path. Maybe I should add a setting allowing users skip path name encryption or warn them about lengthy encrypted results...
