### ISSUE TITLE
can't find settings in obsidian

### ISSUE THREAD

**Issue by xutq** [fyears/remotely-save#13]
Hi, I am using v0.2.9 on both my PC (win 10, obsidian v0.13.19) and iPhone (1.0.5). I installed and enabled this plugin, but can't find settings on both PC and iPhone. How can I deal with this?

**Comment by fyears** [comment]
Could you try to find it in Obsidian settings panel? 

![AD7A9295-A622-495C-874B-D6EEB2A0D0E8](https://user-images.githubusercontent.com/1142836/148347441-32958dce-25b5-4a82-aa8c-6d998db86b77.jpeg)

**Comment by xutq** [comment]
nope on both iphone and PC
![image](https://user-images.githubusercontent.com/15274805/148353611-0206531f-3ed7-40ae-887e-a203380051bb.png)

![2022-01-06_16-24-44](https://user-images.githubusercontent.com/15274805/148353669-6230289a-804c-4de0-bd21-c89405b398c1.jpg)

**Comment by fyears** [comment]
hmmm that’s really unexpected. I will try to do fresh install and check what happened today

**Comment by xutq** [comment]
thank you

**Comment by xutq** [comment]
One of my colleagues encountered the same problem too, but he could find it Obsidian setting panel several days ago.

**Comment by zbqiang8** [comment]
I also can't find settings in obsidian for Android and Windows

**Comment by fyears** [comment]
@xutq @zbqiang8 sorry everyone. Now the bug has been fixed in the latest version 0.2.10 . Please install the latest version and try again.

**Comment by fyears** [comment]
The bug would not affect old users upgrading, but indeed affect new user with fresh installs.
