### ISSUE TITLE
OneDrive 不能上传 大小为0的文件

### ISSUE THREAD

**Issue by KuiyueRO** [fyears/remotely-save#15]
我发现只有onedrive的客户端允许上传 0byte的文件，onedrive的网页端和remotely-sync都不可以

当遇到0kb的文件时，remotely-sync似乎会直接终止同步

是不是可以将其设置为跳过

**Comment by exoticknight** [comment]
有很多0byte文件是有特殊作用的，跳过可能会有更大的问题

**Comment by fyears** [comment]
网页端是不允许的。remotely save 则没有做特别限制，如果是中断了那么推测是 api 阻断了。有空余时间时候我研究一下。

**Comment by fyears** [comment]
经测试，空文件夹可以上传，空文件不可以。

如果没有加密，则跳过空文件上传；
如果加密了，则加密后会变成非空文件，直接上传。

fixed in https://github.com/fyears/remotely-save/releases/tag/0.2.12
