### ISSUE TITLE
Nginx webdav 403 with depth infinity

### ISSUE THREAD

**Issue by umaron** [fyears/remotely-save#17]
403 from [this](https://github.com/arut/nginx-dav-ext-module/blob/f5e30888a256136d9c550bf1ada77d6ea78a48af/ngx_http_dav_ext_module.c#L753)
```
    if (rc == NGX_MAX_INT_T_VALUE) {

        /*
         * RFC4918:
         * 403 Forbidden -  A server MAY reject PROPFIND requests on
         * collections with depth header of "Infinity", in which case
         * it SHOULD use this error with the precondition code
         * 'propfind-finite-depth' inside the error body.
         */

        return NGX_HTTP_FORBIDDEN;
    }
```

**Comment by umaron** [comment]
Maybe you can make a compatibility mode.

**Comment by fyears** [comment]
Thanks. Maybe I should define a large max depth like 1000

**Comment by umaron** [comment]
> Thanks. Maybe I should define a large max depth like 1000

Well, the value of depth of PROPFIND can noly be 0, 1 or infinity, defined in [rfc4918](https://datatracker.ietf.org/doc/html/rfc4918#section-9.1). 
`A client MUST submit a Depth header with a value of "0", "1", or "infinity" with a PROPFIND request.`
I've tested it and got 400 with depth 10.

**Comment by fyears** [comment]
Huh, you’re right. So it basically means that I have to do a dfs manually, by calling depth 1 recursively. It’s indeed possible although consuming many resources. Well, at least better than not working :-(

**Comment by fyears** [comment]
fixed in https://github.com/fyears/remotely-save/commit/320f91f1a50a81619c01e2ba65820c494907aa5d
