### ISSUE TITLE
OneDrive Error

### ISSUE THREAD

**Issue by quanru** [fyears/remotely-save#19]
![image](https://user-images.githubusercontent.com/11739753/150631525-ff397c60-edbf-4c21-8cbe-2d4b5f9bc009.png)

**Comment by fyears** [comment]
I don't know why onedrive api returns path like this. But I try to detect `/Livefolders/应用/` is newer version. You could update and try again.

fixed in https://github.com/fyears/remotely-save/releases/tag/0.2.12
