### ISSUE TITLE
OneDrive prompt "is not a folder, but lacks local mtime"

### ISSUE THREAD

**Issue by quanru** [fyears/remotely-save#20]
![image](https://user-images.githubusercontent.com/11739753/150637625-de62cc17-fbbd-43bf-b337-e8bc7f2db8a4.png)

**Comment by fyears** [comment]
No idea why this happened. It's a file, and Obsidian should capture the local mtime correctly. 

1. Could you please provide the following information?
   OS? Desktop or mobile? Obsidian version? Is your OneDrive the global version or 世纪互联版? 

2. Could you please create am empty vault, and put some random / meaningless folders or files and and try to sync them? Is the error reproducible in the new vault?

**Comment by quanru** [comment]
1. OS: 
![image](https://user-images.githubusercontent.com/11739753/150661309-450a79b9-e637-4e9f-b86e-2f54ed976d2e.png)
Obsidian: 
![image](https://user-images.githubusercontent.com/11739753/150661326-27cd4200-b0a5-4146-9000-a11fce3ace62.png)
OneDrive:
![image](https://user-images.githubusercontent.com/11739753/150661348-5da8753d-7294-4c44-b647-66098b3c3a9a.png)
Normal jpg:
![image](https://user-images.githubusercontent.com/11739753/150661384-f393b66d-b96f-4338-b3d8-dac18eb2eda4.png)
2. 
![image](https://user-images.githubusercontent.com/11739753/150661490-69fd13fb-802a-45e6-b1b5-a6b7e21bff92.png)
3. The error can not reproduce:
![image](https://user-images.githubusercontent.com/11739753/150661578-6432ee35-818b-4ed8-be62-cde817d716a4.png)
And in the new valut, there is only one md file:
![image](https://user-images.githubusercontent.com/11739753/150661640-b570b922-cede-42c9-946f-2dc538124c26.png)

**Comment by fyears** [comment]
Please consider removing some sensitive info on your third screenshot. 

So it may be a bug on Obsidian that app.vault.getAllLoadedFiles(); returns zero mtimes. Please consider raise this bug on https://github.com/obsidianmd/obsidian-api/issues 

cc the author of Obsidian @lishid hi my plugin uses getAllLoadedFiles to get the mtime of files. But the user reports that a zero mtime is returned. Is it the expected behavior that Obsidian app.vault.getAllLoadedFiles(); returns zero mtimes? Thank you so much!

**Comment by fyears** [comment]
@quanru Please consider removing any sensitive info on your sceenshots.

And it seems that the only relevant screenshots are the ones about OS, Obsidian version, and the zero mtime in app.vault.getAllLoadedFiles(). 

Not bugs on OneDrive api so you may delete the Onedrive screenshot.

Reproduced vault screenshot can also be deleted.

Thank you for your report!

**Comment by quanru** [comment]
It is ok, that not sensitive. Thanks for you contribution~

**Comment by quanru** [comment]
> Please consider removing some sensitive info on your screenshots.
> 
> So it may be a bug on Obsidian that app.vault.getAllLoadedFiles(); returns zero mtimes. Please consider raise this bug on https://github.com/obsidianmd/obsidian-api/issues
> 
> cc the author of Obsidian @lishid hi my plugin uses getAllLoadedFiles to get the mtime of files. But the user reports that a zero mtime is returned. Is it the expected behavior that Obsidian app.vault.getAllLoadedFiles(); returns zero mtimes? Thank you so much!

It is seems right return zero, which mean 1970/1/1, it's the time when timestamp begin: https://www.google.com.hk/search?q=timestamp+beginning&newwindow=1&ei=Je3sYfvoNqOLmgeOnJyAAw&oq=timestamp+begin&gs_lcp=Cgdnd3Mtd2l6EAMYATIECAAQEzIGCAAQHhATMgYIABAeEBMyCAgAEAUQHhATMggIABAFEB4QEzIICAAQBRAeEBMyCAgAEAUQHhATMggIABAFEB4QEzIICAAQBRAeEBMyCAgAEAgQHhATOgcIABBHELADOgQIABBDOgUIABCABDoGCAAQDBAeOgQIABAeSgQIQRgASgQIRhgAUJIDWPwLYJYoaAFwAngAgAHHAYgBwQiSAQMwLjaYAQCgAQHIAQfAAQE&sclient=gws-wiz

**Comment by lishid** [comment]
According to the screenshot from Finder, the file is actually tagged with mtime = 0 on disk (1970-01-01). There are some apps that do that which is not in our control. You should not assume that files cannot have `mtime = 0` (same for ctime).

**Comment by fyears** [comment]
Ouch! I missed the screenshot from the Finder. And yes that’s not Obsidian’s issue. Thank you so much for your help! (And sorry for pinging you…) @lishid 


@quanru Would you please verify that whether the mtime (in finder) would be correctly set after some modifications? (For example, change the filename from a to b then change it back to a, which should be harmless) I would see what I can do…

**Comment by quanru** [comment]
@fyears it's so weird, i rename the file, the mtime not change, but i can use command 'touch -t' to modify the mtime. the file can not upload to icloud, too. so it seems not your problem. i will find a tool to modify the mtime in bulk.

**Comment by quanru** [comment]
i use this script modify the mtime and ctime in bulk:
```js
const globby = require('globby');
const execa = require('execa');

globby(
  '~/PARA/**/*'
).then((files) => {
  files.map(file => {
    execa('touch', ['-m', '202101231111', file])
    execa('touch', ['-mt', '202101231111', file])
    execa('Setfile', ['-d', '01/23/2021 11:00:00', file])
  })
  console.log(files);
});

```

it's ok now!

but, there is a new question:
![image](https://user-images.githubusercontent.com/11739753/150680165-00ff6303-c782-435f-8495-05554f55142c.png)
is it better to open a new issue to track the new question?

**Comment by fyears** [comment]
Cool! 

But remember that, when the plugin does sync **next time**, it requires the mtimes correctly being set, otherwise it doesn’t kow what files has been changed between this sync and next sync. Good luck!
