### ISSUE TITLE
Logs for sync conflicts?

### ISSUE THREAD

**Issue by ZainRizvi** [fyears/remotely-save#25]
First of all, it’s awesome to see sync support with OneDrive, thank you!

Now, is there any way to see *why* a sync conflict happened on a mobile device? Are logs stored anywhere perhaps?

I’ve gotten into a state where my mobile device complains about sync errors, but I don’t see a way to tell what the error is and so I can’t manually fix the conflict

**Comment by fyears** [comment]
Hi thanks for your report!

First of all, this plugin doesn’t generate or detect or deal with “sync conflict”. It basically compares the last modified times of the same-name files on the local device and the remote service, and decides the one with later last modified time wins. No conflicts or content merging.

Secondly, you could take a screenshot while the error occurs, at which time some notices should be shown indicating some basic helper info on your screen.

Thirdly, if you are using Android, it’s indeed possible to check the log in the console by connectting your device to a computer, and using the computer Chrome browser to see the logs in the console. https://forum.obsidian.md/t/debugging-obsidian-mobile-plugins/20913

**Comment by ZainRizvi** [comment]
I'm using iOS.  I'm okay with the plugin not detecting sync conflicts, as long as it can tell me which file the conflict is in so that I can manually resolve them!

The screenshot unfortunately doesn't contain any useful info beyond saying that the sync was started and then aborted due to _some_ "error while syncing"
![IMG_0585](https://user-images.githubusercontent.com/4468967/151692260-d2b89a56-8398-4bbf-8be5-bd1bd2847e27.jpg)

I tried using the debug output, but then realized that the debug view only shows up in the console and the console isn't visible in iOS.

Any chance you could extend the debug mode to either also output text to the obsidian Notice or to a separate file that I can open on my phone?

**Comment by ZainRizvi** [comment]
Wow, so I just tried installing the plugin in a fresh vault on my desktop to see if it would repro.

It did, and I got to see the debug console output:

It's getting a CORS error!!!  Thrown by [this line I think](https://github.com/fyears/remotely-save/blob/f7082616aaf7ee824443b61a12e270df4156c138/src/remoteForOnedrive.ts#L666)

![image](https://user-images.githubusercontent.com/4468967/151692476-bfc92c98-bcaa-4ef8-af88-988984a6cd40.png)

[One possible fix](https://forum.obsidian.md/t/make-http-requests-from-plugins/15461/8) seems to be to replace the fetch method with a different api call that tells chrome to ignore the CORS headers returned by the onedrive api. An alternate possibility seems to be to replace the `fetch` call with a `get` request instead.

**Comment by fyears** [comment]
That’s strange, last time I checked, I didn’t meet this cors error. I will try to reproduce it. Would you like to provide specific ways to reproduce it if you have free time, please?

BTW it’s not ok to use node js http module because the plugin uses the browser environment instead of nodejs environment (Mainly because that iOS doesn’t have nodejs, so the choices are limited). But Obsidian provides an alternative api that may be helpful. I would check that out.

**Comment by fyears** [comment]
> I tried using the debug output, but then realized that the debug view only shows up in the console and the console isn't visible in iOS.

Yes you’re right. It’s possible to debug on Android using console, but unfortunately it’s hard to do that on iOS. I personally always try to debug on Desktop firstly.

**Comment by fyears** [comment]
And, what’s your operation system? Mac, Linux, or Windows? What version is the Obsidian? Thanks!

**Comment by fyears** [comment]
A new version tries to avoid cors as much as possible while using onedrive api:

https://github.com/fyears/remotely-save/releases/tag/0.2.14
