### ISSUE TITLE
sync issues

### ISSUE THREAD

**Issue by raanym** [fyears/remotely-save#26]
I have setup on Obsidian on my android phone with remotely sync. I have also set it up with my desktop as well. Right now, I'm trying to delete something from my desktop and then syncing it, the updates are propagated to dropbox. But then when I try to sync those changes to mobile, the mobile is basically re-adding those deleted files (ones I deleted from desktop)

I'm not sure how to fix this, seem's like a problem with export sync mapping.

**Comment by fyears** [comment]
see this: https://github.com/fyears/remotely-save/issues/6

and this: https://github.com/fyears/remotely-save/blob/master/docs/minimal_intrusive_design.md

tldr: Right now deletion operations are not synced. A new algorithm needs to be implemented in the future. a workaround of manually deleting files on all devices is needed currently.
