### ISSUE TITLE
Does not work with Backblaze B2 with S3-compatible API

### ISSUE THREAD

**Issue by jasonekratz** [fyears/remotely-save#27]
More of a note than an issue...

I was trying to get this to work with Backblaze B2 as the sync source since they have an S3 compatibility option. Unfortunately per their support they only support HTTP/HTTPS and do not support custom protocols required by this plugin (app and capacitor).

**Comment by fyears** [comment]
Unfortunately the CORS issue is indeed a problem that requires the server part configured to bypass.

Another possible way is specifying the allowed origin to `*` (a star), meaning **any** origin sources are allowed to make requests to the bucket (I believe it implicitly allows `app://` and `obsidian://`). Or maybe “share everything in this bucket with every origin” is the equivalent way in the screenshot in [this page](https://www.backblaze.com/blog/enable-cors-for-cross-origin-resource-sharing/) . But please remember that you should [**evaluate the risk by yourself beforehand**](https://stackoverflow.com/questions/21480612/security-concerns-about-cors).

**Comment by jasonekratz** [comment]
Yeah tried all of that. Unfortunately it doesn't work. Per Backblaze they don't allow other protocols, just http/s. Was just posting in case someone else tries to use B2 in S3-compatible mode.

**Comment by fyears** [comment]
Even a rule with `*` doesn’t work? Oh no Blackblaze…

**Comment by jasonekratz** [comment]
I can't even put a * in via their UI. I will try to do it via the command line tool they reference in their docs and see if that works.

**Comment by fyears** [comment]
I tried. And it failed. Backblaze doesn't allow non-http(s) origin currently, and Obsidian uses non-standard schemes right now.

There is nothing I could do until Backblaze relaxes this restriction, or Obsidian provides a bypass-cors api that supports binary files.

**Comment by fyears** [comment]
For those who still reading this: it's already supported in Obsidian>=0.13.25 AND latest version of the plugin.

**Comment by n0k0m3** [comment]
Still doesn't work on Android, but this is Obsidian's dev fault for not bring CORS bypass to android release

**Comment by fyears** [comment]
> Still doesn't work on Android

Hi, Android Obsidian does **allow** bypassing cors, but in the old version the implementation has some bugs. The bugs have been fixed now. And as soon as the new version is released, I will add the support back into the plugin.

**Comment by jasonekratz** [comment]
Totally forgot I had put this issue in and just installed the plugin today and found out that it now works with Backblaze! So great. Thank you!
