### ISSUE TITLE
Modification times(mtime?)of files are always changing, resulting in constant synchronization

### ISSUE THREAD

**Issue by troilus** [fyears/remotely-save#29]
Modification times(mtime?)of files are always changing, resulting in constant synchronization.

I noticed that when I didn't modify any file, there was always files that needed to be synced, so I checked the file itself as well as the obsidian console and found that the time of the file changed and the plugin decided to re-upload the file.

I tried to check what program was modifying the file and causing the modification time to change, but at the same time I only found that obsidian has opened and read operations. Could it be that the plugin change the modification time?

Is it possible to use syncthing’s way to judge whether the file has changed, not by the modification time?

![661EBAFD-49C0-406E-AEB5-11A863101012](https://user-images.githubusercontent.com/1055100/153335009-2587eb1e-e0ff-4b43-89a0-b890890e404a.jpeg)

**Comment by fyears** [comment]
1. What remote service are you connecting to? And are you using the latest version of this plugin?
2. What OS? And do you have other plugins or ither programes that may change the mtime?
3. The plugin does NOTHING besides manual sync or auto sync or Obsidian start up. The only moment it changes mtime is when it uploads or downloads files.
4. It’s technically possible to add some meta data like md5 for some remotes to get a better sync experience. (The rclone-way.) But it will not be implemented in the near future.
