### ISSUE TITLE
[Bug]: getting_remote_files_list error while files 1k+

### ISSUE THREAD

**Issue by snowandocean** [fyears/remotely-save#33]
### What happened?

I use Tencent Cloud COS .Tencent Cloud COS is compatible with S3. It can work correctly when files number not too much.

[COS document](https://cloud.tencent.com/document/product/436/7734)

The number of files exceeds 1000, and the synchronization process will be interrupted by error. 

> remotely-save-bucketname: abort sync,triggerSource=manual,error while getting_remote_files_list. 

I'm guessing this error is caused by pagination. I don't know if Amazon S3 has the same problem.

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.1

### Version of Obsidian

0.13.23

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Thanks for your report!

Can you reproduce the error below 1000 files?( In another test vault) And what error shows in the screen?

I SHOULD have added pagination. But let me also generate 1000 files and try again when I have free time to see if any bugs.

**Comment by 1657744680** [comment]
我用的阿里云oss，它有个限制：“单个Bucket最多只能配置1000条清单规则。”
是不是这个原因呢？

**Comment by 1657744680** [comment]
> Thanks for your report!
> 
> I SHOULD have added pagination. But let me also generate 1000 files and try again when I have free time to see if any bugs.

i use aliyun oss（s3），and i have the same bug😥

**Comment by fyears** [comment]
Hi all,

There is a bug in my pagination function. I have fixed this in https://github.com/fyears/remotely-save/commit/55890611e25d860d5da764c89c87a3bb2b738649 

The fix will be released in next version of the plugin.

Thanks!

**Comment by fyears** [comment]
It's released in 0.3.2. Please give it a try. Thanks!

**Comment by 1657744680** [comment]
> It's released in 0.3.2. Please give it a try. Thanks!

thanks for your work，it‘s fixed👍
