### ISSUE TITLE
[Bug]: DropBox

### ISSUE THREAD

**Issue by niksingh710** [fyears/remotely-save#34]
### What happened?

DropBox URL does not open the current instance of the vault and does not get verified.

It opens another instance of the obsidian.

### What OS are you using?

Linux

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.1

### Version of Obsidian

0.13.23

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
What operation are you using? Ubuntu 21.04?

I am sure that in Windows the Obsidian would jump back.

That being said, I would like to add the option of using codes

**Comment by fyears** [comment]
Could you please press ctrl+shift+i  , then input `navigator.userAgent` to see the result? Thanks

**Comment by niksingh710** [comment]
> What OS are you using? Ubuntu 21.04?
> 
> I am sure that in Windows the Obsidian would jump back.
> 
> That being said, I would like to add the option of using codes

I am using Kubuntu 21.10

**Comment by niksingh710** [comment]
> Could you please press ctrl+shift+i , then input `navigator.userAgent` to see the result? Thanks

```
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.13.23 Chrome/91.0.4472.164 Electron/13.6.2 Safari/537.36"
```

This is the output I got.

**Comment by fyears** [comment]
Thanks.

And I add a fallback (to code paste) for Linux in 0.3.2 , please upgrade the plugin and try again!
