### ISSUE TITLE
[Bug]: Some files are lost when syncing with OneDrive 【OneDrive 同步会丢失部分文件】

### ISSUE THREAD

**Issue by iamalexblue** [fyears/remotely-save#40]
## 问题描述
目前尝试了 dropbox、 WebDAV、 OneDrive 三个同步方式，发现坚果云 WebDAV 无法正常连接，可能是配置有什么问题，dropbox 倒是可以正常配置，但是无法同步，onedrive 倒是可以同步，但是在 pc 端上传的时候貌似会丢失部分文件，因为我是同时将笔记库放在 GitHub 上，用 OneDrive 同步完成之后发现 GitHub 有文件变动。然后我又手动在回收站找回了文件再次通过 obsidian 同步，文件再次被删除了。

因此可以初步确定同步过程中会删除部分文件，不知道是什么原因导致的。

![image](https://user-images.githubusercontent.com/41639269/157680349-447131b5-0fe4-40aa-8c99-a4f15bf3cdfd.png)

不知道是不是 OneDrive 同步有什么文件格式限制之类的，部分文件在同步的过程中无法正常同步到 onedrive。
（在 issue 看到有人用中文提 issue，点进去查看了一下作者的首页发现是国人，于是用中文写了 issue，如果开发者觉得不太好的话在这里表示抱歉）

如果需要提供一些更详细的内容的话可进一步讨论

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal, Dropbox, webdav

### Version of the plugin

0.3.4

### Version of Obsidian

v0.13.31

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by troilus** [comment]
坚果云的webdav不支持CORS
`Currently webdav server has to be enabled CORS for requests from app://obsidian.md and capacitor://localhost and http://localhost, AND all webdav HTTP methods, AND all webdav headers. These are required, because Obsidian mobile works like a browser and mobile plugins are limited by CORS policies.`

**Comment by fyears** [comment]
> 中文 issue

完全可以！欢迎多用多提意见或者 bug！

> 上传到 git

注意！！！！！ 这个插件的 `data.json` 包含了一些敏感信息，**强烈不建议**把它塞到 git 里面！！！！

建议：首先把 git repo 私有，然后撤销现有的授权：

* 坚果云： https://help.jianguoyun.com/?p=2064 “撤销授权”按钮
* Dropbox：  https://www.dropbox.com/account/connected_apps
* OneDrive： https://microsoft.com/consent

然后从 git 历史删除 `data.json`。

> 坚果云是否支持

这里依赖 Obsidian 新的 api。使用桌面版 Obsidian >= 0.3.25 （官网已更新） &&  Remotely Save >= 0.3.5 可以尝试使用！（支持新 api 的手机版 Obsidian 还在内测）。

> OneDrive 文件被删除

请按照[这里](https://github.com/fyears/remotely-save/blob/0.3.5/docs/how_to_debug/export_sync_plans.md)，导出和查看 sync plan。

中文概要版：

1. 停止自动更新
2. "Debug" -> "export sync plans", 按钮 "Export"
3. 查看生成的文件 `_debug_remotely_save/sync_plans_hist_exported_on_{a_timestamp}.md`，里面有 json 代表 sync plan
4. 在 json 里找到你认为被删除的文件，看看 `mtimeRemote`, `deltimeRemote`, `mtimeLocal`, `deltimeLocal` 字段是否正常（这是时间戳格式），然后看看 `decision` `decisionBranch` 是啥。一般来说很有可能是某个时间戳不正常。
5. 如果要贴 sync plan 的一部分上来的话，**强烈建议**只贴关键部分，**而且移除文件名、文件夹名等敏感信息**。

**Comment by troilus** [comment]
> 

0.3.5起的webdav可以不启用CORS了吗？

**Comment by fyears** [comment]
> 0.3.5起的移动版使用webdav可以不启用服务器的CORS了吗？

是的，可以试试，我测试 ok

**Comment by iamalexblue** [comment]
感谢开发者回复，没及时回复，我按照您的提示重置了仓库，然后重新配置 Onedrive 同步，现在可以正常同步了，感谢开发出如此强的扩展😄

**Comment by TIANTIANSTUDY** [comment]
非常感谢开发出如此强大的插件！
