### ISSUE TITLE
[Bug]: 0.3.5，PC端支持绕过cors，但是移动端还是不支持

### ISSUE THREAD

**Issue by zhaochuanwen** [fyears/remotely-save#42]
### What happened?

您好，
我试用了0.3.5版本的插件
在PC端win10，成功设置了坚果云
但是ios和安卓，依旧需要cors
请问这个是什么原因导致的呢？未来移动端会支持绕过cors吗

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.5

### Version of Obsidian

0.13.31

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
正如之前所说，这个是用到了 obsidian 新的 api。电脑版已经发布了，但是手机版还在内测，因此要使用内测版obsdian或者等待新版本发布。它那边发布了之后更新了之后就会支持了。

**Comment by fyears** [comment]
抱歉，这里忘记加文档了（代码刚发布，文档还没更新）。我抽空在文档里说明一下。
