### ISSUE TITLE
[Bug]:  skipping _ and . files

### ISSUE THREAD

**Issue by pcause** [fyears/remotely-save#45]
### What happened?

the plugin says it won't copy files starting with _ or ,  I moved from another note taking services and it puts images in a directory called _resources.  I need that copied.  Also, I'd think folks want to also copy the .obsidian directory as well.  Allow this by perhaps allowing a user to specify a list of otherwise ignored directories to include.

### What OS are you using?

Windows

### What remote cloud services are you using?

others

### Version of the plugin

0.3.5

### Version of Obsidian

latest insider

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
duplicated of https://github.com/fyears/remotely-save/issues/9

I would like to think about it later

**Comment by fyears** [comment]
Fixed in https://github.com/fyears/remotely-save/releases/tag/0.3.6

You can enable `_` files and `.obsidian` config dir syncing in the settings (in the Advanced section) Other genreral `.` files are not going to be supported.
