### ISSUE TITLE
[Bug]: files with special characters get duplicated

### ISSUE THREAD

**Issue by imeed166** [fyears/remotely-save#46]
### What happened?

Files that have letters with special characters in the title, like `é` or `à` get duplicated and renamed with weird symbols.

Here are some examples :
1. `éco-gestes.md` get duplicated, and the new file is `e╠üco-gestes.md`
2. `aversion à la perte.md` get duplicated, and the new file is `aversion a╠Ç la perte`

### What OS are you using?

macOS, Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.5

### Version of Obsidian

0.13.33

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Could you please try to directly upload the file to dropbox (using their web interface), to see what happened?

**Comment by fyears** [comment]
Interesting, I could reproduce the bug using dropbox's web interface (upload and download). So I guess Dropbox side is doing something to normalize the file name. I suggest you directly report an issue to them (using the web interface example). I would like to respect what dropbox's api returns and avoid doing extra things.

Another possible option is using this plugin's encryption mode, by adding a password. So the file name will be changed to english letter and number, so no weird thing would happen.

**Comment by imeed166** [comment]
Okay, I'll do what you suggested, thank you.
