### ISSUE TITLE
[Bug]: Cannot connect to webdav for Seafile in mobile app

### ISSUE THREAD

**Issue by conql** [fyears/remotely-save#54]
### What happened?

It works fine in desktop app, but not for mobile app. My server can receive request from mobile, but always respond 401.

nginx log:

06.119.184.13 - - [17/Mar/2022:18:12:10 +0000] "OPTIONS /seafdav/Storage/notes HTTP/1.1" 401 139 "http://localhost/" "Mozilla/5.0 (Linux; Android 12; Redmi K30 Build/SKQ1.210908.001; wv) 

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.6

### Version of Obsidian

1.1.0

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by conql** [comment]
加上authorization之后的回应。
![Screenshot_2022-03-18-03-01-31-256_com guoshi httpcanary](https://user-images.githubusercontent.com/49243542/158877322-3cfbd591-13ca-4448-a087-ca3545571bab.jpg)

**Comment by fyears** [comment]
请问手机上的webdav设置了账号和密码了吗？

**Comment by fyears** [comment]
此外手机上的 auth type 选择了 basic 了吗？

**Comment by conql** [comment]
设置了账号密码和authtype basic。也尝试使用过电脑的配置文件，都无法连接。

**Comment by conql** [comment]
看了下log，是cors的问题。

Solution: Modify nginx config to add cors
```
if ($request_method = OPTIONS ) {
	add_header Content-Length 0;
	add_header Content-Type text/plain;
	add_header DAV 1,2;
	add_header Allow 'OPTIONS,HEAD,GET,PROPFIND,DELETE,COPY,MOVE,PROPPATCH,LOCK,UNLOCK';
	add_header Access-Control-Allow-Origin '$http_origin' always;
	add_header Access-Control-Allow-Credentials 'true' always;
	add_header Access-Control-Allow-Methods 'OPTIONS,HEAD,GET,POST,PUT,PROPFIND,DELETE,COPY,MOVE,PROPPATCH,LOCK,UNLOCK' always;
	add_header Access-Control-Allow-Headers '*' always;
	return 200;
}

add_header Access-Control-Allow-Origin '$http_origin' always;
add_header Access-Control-Allow-Credentials 'true' always;
add_header Access-Control-Allow-Methods 'OPTIONS,HEAD,GET,POST,PUT,PROPFIND,DELETE,COPY,MOVE,PROPPATCH,LOCK,UNLOCK' always;
add_header Access-Control-Allow-Headers 'Origin,X-Requested-With,Content-Type,Accept,Authorization,Depth' always;

**Comment by fyears** [comment]
谢谢反馈，看上去是 preflight request 的问题。

等最新版本的移动版obs内测结束了，本插件就会自动支持跳过cors了。届时nginx的配置也可以恢复原状，不需要为cors定制。
