### ISSUE TITLE
Onedrive Error

### ISSUE THREAD

**Issue by chen860456552** [fyears/remotely-save#8]
Hello ,it is a great plugin , but when i use OneDrive to sync , it has a error. I  don't konw how to solve it

**Comment by fyears** [comment]
Hi, it seems that the path folder is `/drive/root/:应用/remotely-save` instead of `/drive/root/:App/remotely-save` so the plugin doesn't recognize it. I will try to fix the issue in the next release.

(And I edited your post, deleted the screenshot to avoid any info leaking)

**Comment by fyears** [comment]
Hi, this is fixed in [the latest version 0.2.7](https://github.com/fyears/remotely-save/releases/tag/0.2.7) .

You can directly update the plugin to 0.2.7 from Obsidian "Community plugins" settings.

**Comment by chen860456552** [comment]
Wow, I updated it, this time there is no error.Now I can give up Joplin.Thank you so much.




---Original---
From: ***@***.***&gt;
Date: Mon, Jan 3, 2022 01:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fyears/remotely-save] Onedrive Error (Issue #8)




 
Hi, this is fixed in the latest version 0.2.7 .
 
You can directly update the plugin to 0.2.7 from Obsidian "Community plugins" settings.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
