### ISSUE TITLE
ignoring of files and folders starting with . and _ ?

### ISSUE THREAD

**Issue by corollary-wisp** [fyears/remotely-save#9]
Hi fyears, I'm very much enjoying this plugin! Thanks for making it, this could be a gamechanger for so many people! I'm just wondering, why are files/folders starting with . and _ ignored during sync, and is it possible for this to change in a future update? For me and likely many others, this would be really useful  for syncing the config folders (e.g. .obsidian folder) between devices. This is especially a pain point with iPadOS which makes it difficult to copy files (especially 'system' files) in from outside the iPad. That's the only issue for me with the current version of the plugin.

**Comment by fyears** [comment]
1. Basically, `.` is THE hidden file prefix on Linux and Mac. And `_` is just a convenient convention (randomly chosen by me) for users to tell the plugin that "the file should not be synced but it's editable and viewable on Obsidian and OS".
2. So your intention might be "syncing the `.obsidian` folder", or "syncing ALL hidden files starting with `.`". They are different and the previous one is more accurate IMO.
3. For the ability to "syncing the `.obsidian` folder", it depends on whether Obsidian [exposes some api to list all files inside it](https://github.com/obsidianmd/obsidian-api/issues/34). Maybe it's possible but I don't know it yet. I will leave this issue opened, but this is not in my high priority roadmap, sorry.

**Comment by fyears** [comment]
Fixed in https://github.com/fyears/remotely-save/releases/tag/0.3.6

You can enable `_` files and `.obsidian` config dir syncing in the settings (in the Advanced section) Other genreral `.` files are not going to be supported.

**Comment by zddd** [comment]
> Fixed in https://github.com/fyears/remotely-save/releases/tag/0.3.6
> 
> You can enable `_` files and `.obsidian` config dir syncing in the settings (in the Advanced section) Other genreral `.` files are not going to be supported.

Just wondering tho, why is .git folder ignored? Is there any limitations technically?
It's a great plugin, THX for your work!

**Comment by fyears** [comment]
That's because Obsidian's api by default ignores all dot files including `.git`. Furthermore, it's rather a bad idea to use sync method to sync `.git` folder, and you are suggested to directly use git commands to manage git repos.
